server:
  port: 8443

spring:
  datasource:
    username: root
    password: 123456
    url: jdbc:mysql://localhost:3306/white_jotter?useUnicode=true&characterEncoding=utf-8&useSSL=true&serverTimezone=UTC
    driver-class-name: com.mysql.cj.jdbc.Driver
    type: com.alibaba.druid.pool.DruidDataSource

mybatis:
  mapper-locations: classpath:mapper/*Mapper.xml
  type-aliases-package: com.wx.wj.pojo
